server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/takeout_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root         # 改成你的 MySQL 用户名
    password: shuai2022594618         # 改成你的 MySQL 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

